# Generated by Django 6.0 on 2025-12-21 08:02

import django.db.models.deletion
import farm_infra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(help_text='Unique name for the farm', max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmAudits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField()),
                ('auditor_name', models.CharField(max_length=150)),
                ('report', models.TextField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.farmbasic')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.farmbasic')),
            ],
        ),
        migrations.CreateModel(
            name='FarmLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.farmbasic')),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(help_text='Max birds', validators=[farm_infra.models.validate_non_zero])),
                ('type', models.CharField(choices=[('Layer', 'Layer'), ('Broiler', 'Broiler'), ('Breeder', 'Breeder')], max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.farmbasic')),
            ],
            options={
                'verbose_name_plural': 'Houses / Sheds',
                'unique_together': {('farm', 'house_name')},
            },
        ),
        migrations.CreateModel(
            name='HouseSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[farm_infra.models.validate_positive])),
                ('ventilation_type', models.CharField(max_length=100)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.houses')),
            ],
        ),
        migrations.CreateModel(
            name='HouseUtilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity', models.BooleanField(default=True)),
                ('water_source', models.CharField(max_length=100)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.houses')),
            ],
        ),
        migrations.CreateModel(
            name='FarmOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_contact', models.CharField(help_text='Format: 03001234567', max_length=15, validators=[farm_infra.models.validate_phone])),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.farmbasic')),
            ],
            options={
                'unique_together': {('farm', 'owner_name', 'owner_contact')},
            },
        ),
    ]
