# Generated by Django 6.0 on 2025-12-18 16:47

import django.db.models.deletion
import farm_infra.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_infra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houses',
            options={'verbose_name_plural': 'Houses / Sheds'},
        ),
        migrations.AlterField(
            model_name='farmbasic',
            name='farm_name',
            field=models.CharField(help_text='Unique name for the farm', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='farmlocation',
            name='farm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.farmbasic'),
        ),
        migrations.AlterField(
            model_name='farmownership',
            name='owner_contact',
            field=models.CharField(help_text='Format: 03001234567', max_length=15, validators=[farm_infra.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='houses',
            name='capacity',
            field=models.IntegerField(help_text='Max birds', validators=[farm_infra.validators.validate_non_zero]),
        ),
        migrations.AlterField(
            model_name='housespecs',
            name='floor_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[farm_infra.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='housespecs',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.houses'),
        ),
        migrations.AlterField(
            model_name='houseutilities',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.houses'),
        ),
        migrations.AlterUniqueTogether(
            name='houses',
            unique_together={('farm', 'house_name')},
        ),
    ]
