# Generated by Django 6.0 on 2025-12-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_infra', '0002_alter_houses_options_alter_farmbasic_farm_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farmownership',
            unique_together={('farm', 'owner_name', 'owner_contact')},
        ),
    ]
