# Generated by Django 6.0 on 2025-12-25 09:55

import farm_infra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_infra', '0003_alter_farmownership_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmownership',
            name='owner_contact',
            field=models.CharField(help_text='Format: 03001234567', max_length=15, validators=[farm_infra.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='houses',
            name='capacity',
            field=models.IntegerField(help_text='Max birds', validators=[farm_infra.models.validate_non_zero]),
        ),
        migrations.AlterField(
            model_name='housespecs',
            name='floor_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[farm_infra.models.validate_positive]),
        ),
    ]
