# Generated by Django 6.0 on 2026-01-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_infra', '0004_alter_farmownership_owner_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionprojects',
            options={'verbose_name': 'ConstructionProjects', 'verbose_name_plural': 'ConstructionProjects'},
        ),
        migrations.AlterModelOptions(
            name='farmaudits',
            options={'verbose_name': 'Audits', 'verbose_name_plural': 'Audits'},
        ),
        migrations.AlterModelOptions(
            name='housespecs',
            options={'verbose_name': 'Houses & Specs', 'verbose_name_plural': 'Houses & Specs'},
        ),
        migrations.AlterModelOptions(
            name='houseutilities',
            options={'verbose_name': 'Utilities', 'verbose_name_plural': 'Utilities'},
        ),
    ]
