# Generated by Django 6.0 on 2025-12-18 17:11

import assets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingbasic',
            name='building_code',
            field=models.CharField(help_text='Unique Identifier (e.g., BLD-001)', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='buildingspecs',
            name='construction_year',
            field=models.IntegerField(help_text='YYYY Format', validators=[assets.validators.validate_construction_year]),
        ),
        migrations.AlterField(
            model_name='ownerbasic',
            name='owner_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='ownercontact',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='ownercontact',
            name='phone',
            field=models.CharField(help_text='Format: 03001234567', max_length=15, validators=[assets.validators.validate_phone]),
        ),
    ]
