# Generated by Django 6.0 on 2025-12-25 09:55

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_buildingbasic_building_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingspecs',
            name='construction_year',
            field=models.IntegerField(help_text='YYYY Format', validators=[assets.models.validate_construction_year]),
        ),
        migrations.AlterField(
            model_name='ownercontact',
            name='phone',
            field=models.CharField(help_text='Format: 03001234567', max_length=15, validators=[assets.models.validate_phone]),
        ),
    ]
