# Generated by Django 6.0 on 2025-12-21 08:02

import django.db.models.deletion
import django.utils.timezone
import hr_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(help_text='13 digits without dashes', max_length=13, unique=True, validators=[hr_admin.models.validate_cnic], verbose_name='CNIC')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTrainingPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=150)),
                ('provider', models.CharField(max_length=150)),
                ('duration_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('state_province', models.CharField(max_length=100, verbose_name='Province/State')),
                ('city', models.CharField(max_length=100)),
                ('town_area', models.CharField(max_length=150, verbose_name='Town/Area')),
                ('street', models.CharField(max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_rural_area', models.BooleanField(default=False, verbose_name='Is Rural Area?')),
                ('rural_landmark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('tax_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(help_text='14-16 Digits', max_length=20, unique=True, validators=[hr_admin.models.validate_account_number])),
                ('iban', models.CharField(help_text='PKxx... (Total 24 chars)', max_length=24, unique=True, validators=[hr_admin.models.validate_pk_iban])),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half-day', 'Half-day'), ('Remote', 'Remote')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('user_role', models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Employee', 'Employee'), ('Manager', 'Manager')], max_length=20)),
                ('access_level', models.IntegerField(default=1)),
                ('rfid_card_number', models.CharField(blank=True, help_text='Exactly 10 Hex characters (0-9, A-F)', max_length=10, null=True, unique=True, validators=[hr_admin.models.validate_rfid])),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to='hr_admin.employeebasic')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=150)),
                ('policy_number', models.CharField(max_length=80)),
                ('coverage_details', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=20)),
                ('work_location', models.CharField(choices=[('Branch', 'Branch'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated'), ('Retired', 'Retired')], max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_admin.branches')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=20)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_approved', to='hr_admin.employeebasic')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('Hourly', 'Hourly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_grade', models.CharField(max_length=50)),
                ('bonus_eligible', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField()),
                ('reason', models.TextField()),
                ('exit_interview_notes', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTrainingRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeetrainingprograms')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[hr_admin.models.validate_phone])),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_admin.owneraddress')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField()),
                ('old_job_title', models.CharField(max_length=100)),
                ('new_job_title', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(max_length=80)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.employeebasic')),
                ('tax_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_admin.taxregion')),
            ],
        ),
    ]
