# Generated by Django 6.0 on 2026-01-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0002_todoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branches',
            options={'verbose_name': 'Branches', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='employeeaccess',
            options={'verbose_name': 'Access', 'verbose_name_plural': 'Access'},
        ),
        migrations.AlterModelOptions(
            name='owneraddress',
            options={'verbose_name': 'Owner Address', 'verbose_name_plural': 'Owner Address'},
        ),
    ]
