# Generated by Django 6.0 on 2025-12-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=150)),
                ('building_code', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_capacity', models.IntegerField()),
                ('power_backup', models.BooleanField(default=False)),
                ('internet_available', models.BooleanField(default=False)),
                ('security_system', models.CharField(choices=[('CCTV', 'CCTV'), ('Guard', 'Guard'), ('None', 'None'), ('Mixed', 'Mixed')], max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.buildingbasic')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingInspections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspector_name', models.CharField(max_length=150)),
                ('report', models.TextField()),
                ('status', models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Follow-up Required', 'Follow-up Required')], max_length=30)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.buildingbasic')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.buildingbasic')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.IntegerField()),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Sq Meters', max_digits=12)),
                ('construction_year', models.IntegerField()),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Needs Renovation', 'Needs Renovation')], max_length=20)),
                ('occupancy_status', models.CharField(choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant'), ('Under Construction', 'Under Construction')], max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.buildingbasic')),
            ],
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Valid', 'Valid'), ('Expired', 'Expired'), ('Revoked', 'Revoked')], max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.buildingbasic')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ownerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_contact', models.CharField(max_length=150)),
                ('emergency_contact', models.CharField(max_length=150)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.buildingbasic')),
                ('manager_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_admin.employeebasic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ownerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ownerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='Permits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Valid', 'Valid'), ('Expired', 'Expired'), ('Revoked', 'Revoked')], max_length=20)),
                ('issued_by', models.CharField(max_length=150)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.buildingbasic')),
            ],
        ),
    ]
