# Generated by Django 6.0 on 2025-12-14 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'hr_admin_employeebasic',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='buildingbasic',
            options={'verbose_name_plural': 'Building Basics'},
        ),
        migrations.AlterModelOptions(
            name='buildingfacilities',
            options={'verbose_name_plural': 'Building Facilities'},
        ),
        migrations.AlterModelOptions(
            name='buildinginspections',
            options={'verbose_name_plural': 'Building Inspections'},
        ),
        migrations.AlterModelOptions(
            name='buildinglocation',
            options={'verbose_name_plural': 'Building Locations'},
        ),
        migrations.AlterModelOptions(
            name='buildingmanagement',
            options={'verbose_name_plural': 'Building Management'},
        ),
        migrations.AlterModelOptions(
            name='buildingspecs',
            options={'verbose_name_plural': 'Building Specs'},
        ),
        migrations.AlterModelOptions(
            name='licenses',
            options={'verbose_name_plural': 'Licenses'},
        ),
        migrations.AlterModelOptions(
            name='owneraddress',
            options={'verbose_name_plural': 'Owner Addresses'},
        ),
        migrations.AlterModelOptions(
            name='ownerbasic',
            options={'verbose_name_plural': 'Owner Basics'},
        ),
        migrations.AlterModelOptions(
            name='ownercontact',
            options={'verbose_name_plural': 'Owner Contacts'},
        ),
        migrations.AlterModelOptions(
            name='permits',
            options={'verbose_name_plural': 'Permits'},
        ),
        migrations.AlterField(
            model_name='buildingmanagement',
            name='manager_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.employeebasic'),
        ),
    ]
