# Generated by Django 6.0 on 2025-12-22 04:42

import django.db.models.deletion
import supply_finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(help_text='Format: 03001234567', max_length=15, unique=True, validators=[supply_finance.models.validate_phone])),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=150, unique=True)),
                ('contact', models.CharField(help_text='Format: 03001234567', max_length=15, validators=[supply_finance.models.validate_phone])),
            ],
        ),
        migrations.CreateModel(
            name='FeedTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[supply_finance.models.validate_positive])),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_finance.expensecategories')),
            ],
        ),
        migrations.CreateModel(
            name='FeedPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='In kg/bags', max_digits=10, validators=[supply_finance.models.validate_non_zero])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[supply_finance.models.validate_positive])),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_finance.feedsuppliers')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_finance.feedtypes')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[supply_finance.models.validate_positive])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_finance.customers')),
            ],
        ),
    ]
