# Generated by Django 6.0 on 2025-12-18 17:17

import supply_finance.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='contact',
            field=models.CharField(help_text='Format: 03001234567', max_length=15, unique=True, validators=[supply_finance.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='expensecategories',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='farmexpenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[supply_finance.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='feedpurchases',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[supply_finance.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='feedpurchases',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='In kg/bags', max_digits=10, validators=[supply_finance.validators.validate_non_zero]),
        ),
        migrations.AlterField(
            model_name='feedsuppliers',
            name='contact',
            field=models.CharField(help_text='Format: 03001234567', max_length=15, validators=[supply_finance.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='feedsuppliers',
            name='supplier_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='feedtypes',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[supply_finance.validators.validate_positive]),
        ),
    ]
