# Generated by Django 6.0 on 2026-01-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_finance', '0003_alter_customers_contact_alter_farmexpenses_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Customers', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='farmexpenses',
            options={'verbose_name': 'Expenses Categories', 'verbose_name_plural': 'Expenses Categories'},
        ),
        migrations.AlterModelOptions(
            name='feedpurchases',
            options={'verbose_name': 'Feed Purchases', 'verbose_name_plural': 'Feed Purchases'},
        ),
        migrations.AlterModelOptions(
            name='feedsuppliers',
            options={'verbose_name': 'Feed Suppliers', 'verbose_name_plural': 'Feed Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='feedtypes',
            options={'verbose_name': 'Feed Types', 'verbose_name_plural': 'Feed Types'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sales', 'verbose_name_plural': 'Sales'},
        ),
    ]
