# Generated by Django 6.0 on 2025-12-21 08:02

import django.db.models.deletion
import poultry_ops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_infra', '0001_initial'),
        ('hr_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdBreeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Layer', 'Layer'), ('Broiler', 'Broiler')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(help_text='Unique Identifier (e.g., BATCH-2025-01)', max_length=80, unique=True)),
                ('quantity', models.IntegerField(validators=[poultry_ops.models.validate_non_zero])),
                ('arrival_date', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_infra.houses')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_ops.birdbreeds')),
            ],
        ),
        migrations.CreateModel(
            name='EggCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('eggs_collected', models.IntegerField(validators=[poultry_ops.models.validate_positive])),
                ('broken', models.IntegerField(default=0, validators=[poultry_ops.models.validate_positive])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_ops.batches')),
            ],
        ),
        migrations.CreateModel(
            name='FarmTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], max_length=20)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_admin.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='MortalityRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(help_text='Number of birds died', validators=[poultry_ops.models.validate_positive])),
                ('cause', models.CharField(max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_ops.batches')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField()),
                ('dose', models.CharField(max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_ops.batches')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_ops.vaccines')),
            ],
        ),
        migrations.CreateModel(
            name='VetVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('vet_name', models.CharField(max_length=150)),
                ('findings', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_ops.batches')),
            ],
        ),
    ]
