# Generated by Django 6.0 on 2025-12-18 16:58

import poultry_ops.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='batch_code',
            field=models.CharField(help_text='Unique Identifier (e.g., BATCH-2025-01)', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='batches',
            name='quantity',
            field=models.IntegerField(validators=[poultry_ops.validators.validate_non_zero]),
        ),
        migrations.AlterField(
            model_name='birdbreeds',
            name='breed_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='broken',
            field=models.IntegerField(default=0, validators=[poultry_ops.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='eggs_collected',
            field=models.IntegerField(validators=[poultry_ops.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='mortalityrecords',
            name='count',
            field=models.IntegerField(help_text='Number of birds died', validators=[poultry_ops.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='vaccine_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
