# Generated by Django 6.0 on 2025-12-25 09:55

import poultry_ops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_ops', '0002_alter_batches_batch_code_alter_batches_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='quantity',
            field=models.IntegerField(validators=[poultry_ops.models.validate_non_zero]),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='broken',
            field=models.IntegerField(default=0, validators=[poultry_ops.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='eggs_collected',
            field=models.IntegerField(validators=[poultry_ops.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='mortalityrecords',
            name='count',
            field=models.IntegerField(help_text='Number of birds died', validators=[poultry_ops.models.validate_positive]),
        ),
    ]
