# Generated by Django 6.0 on 2026-01-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_ops', '0003_alter_batches_quantity_alter_eggcollection_broken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_egg_production', models.IntegerField(default=0, help_text='Total eggs collected today')),
                ('current_tray_price', models.DecimalField(decimal_places=0, default=125, help_text='Current market price per tray', max_digits=10)),
                ('avg_egg_weight', models.CharField(default='58g - 69g', help_text='e.g. 60g', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Farm Status (Website)',
            },
        ),
        migrations.AlterModelOptions(
            name='batches',
            options={'verbose_name': 'Batches', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='birdbreeds',
            options={'verbose_name': 'Breeds', 'verbose_name_plural': 'Breeds'},
        ),
        migrations.AlterModelOptions(
            name='farmtasks',
            options={'verbose_name': 'Farm Tasks', 'verbose_name_plural': 'Farm Tasks'},
        ),
        migrations.AlterModelOptions(
            name='mortalityrecords',
            options={'verbose_name': 'Mortality Records', 'verbose_name_plural': 'Mortality Records'},
        ),
        migrations.AlterModelOptions(
            name='vaccinerecords',
            options={'verbose_name': 'Vaccines Records', 'verbose_name_plural': 'Vaccines Records'},
        ),
        migrations.AlterModelOptions(
            name='vaccines',
            options={'verbose_name': 'Vaccines', 'verbose_name_plural': 'Vaccines'},
        ),
        migrations.AlterModelOptions(
            name='vetvisits',
            options={'verbose_name': 'Vet Visists', 'verbose_name_plural': 'Vet Visits'},
        ),
    ]
