# Generated by Django 6.0 on 2026-01-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_ops', '0004_farmstatus_alter_batches_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmstatus',
            name='avg_egg_weight',
        ),
        migrations.AlterField(
            model_name='farmstatus',
            name='current_tray_price',
            field=models.DecimalField(decimal_places=0, default=125, help_text='Current market price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='farmstatus',
            name='daily_egg_production',
            field=models.IntegerField(default=3500, help_text='Total eggs collected today'),
        ),
    ]
