# Generated by Django 6.0 on 2026-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_ops', '0005_remove_farmstatus_avg_egg_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmstatus',
            name='daily_egg_production',
        ),
        migrations.AddField(
            model_name='farmstatus',
            name='box_price',
            field=models.DecimalField(decimal_places=0, default=10800, help_text='Price of 1 Box (12 Trays / 360 Eggs)', max_digits=10),
        ),
        migrations.AddField(
            model_name='farmstatus',
            name='single_egg_price',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Price of 1 Egg', max_digits=5),
        ),
        migrations.AlterField(
            model_name='farmstatus',
            name='current_tray_price',
            field=models.DecimalField(decimal_places=0, default=900, help_text='Price of 1 Tray (30 Eggs)', max_digits=10),
        ),
    ]
