# Generated by Django 6.0 on 2026-01-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_ops', '0006_remove_farmstatus_daily_egg_production_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmstatus',
            options={'verbose_name_plural': 'Daily Rates & Stock'},
        ),
        migrations.AddField(
            model_name='farmstatus',
            name='eggs_in_stock',
            field=models.BooleanField(default=True, help_text='Uncheck if Eggs are Sold Out'),
        ),
        migrations.AddField(
            model_name='farmstatus',
            name='hens_in_stock',
            field=models.BooleanField(default=False, help_text='Check if Cull Birds are available for sale'),
        ),
        migrations.AlterField(
            model_name='farmstatus',
            name='box_price',
            field=models.DecimalField(decimal_places=0, default=10800, max_digits=10),
        ),
        migrations.AlterField(
            model_name='farmstatus',
            name='current_tray_price',
            field=models.DecimalField(decimal_places=0, default=900, max_digits=10),
        ),
        migrations.AlterField(
            model_name='farmstatus',
            name='single_egg_price',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
    ]
